# -*- coding: utf-8 -*-
"""Restaurant_Data_Analysis_Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qj2K33Q_PEuuymkRqSGriFCzqLqakrOm
"""

# Python code for Restaurant Data ANalytics and Knowledge
import json
import re
import csv
from io import StringIO
from collections import defaultdict

def safe_float(x):
    try:
        if x is None:
            return 0.0
        s = str(x).strip()
        s = s.replace("$", "").replace(",", "").replace("%", "")
        return float(s)
    except:
        return 0.0

def clean_text(s):
    if s is None:
        return ""
    s = str(s)
    s = s.replace("\ufeff", "")
    s = s.replace("\u200b", "")
    s = s.replace("\xa0", " ")
    return s.strip()

def normalize_col(name):
    name = clean_text(name).lower()
    name = re.sub(r"[^a-z0-9]+", "_", name)
    name = re.sub(r"_+", "_", name).strip("_")
    return name

def preprocess_text(text):
    text = str(text)
    text = text.replace("\\n", "\n").replace("\\t", "\t")
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    return text.strip()

def looks_like_pipe_table(text):
    lines = [line.strip() for line in text.splitlines() if line.strip()]
    pipe_lines = [line for line in lines if "|" in line]
    return len(pipe_lines) >= 3

def parse_csv_text(text):
    f = StringIO(text)
    reader = csv.DictReader(f)
    rows = []

    if not reader.fieldnames:
        return [], []

    fieldnames = [normalize_col(c) for c in reader.fieldnames]

    for row in reader:
        cleaned_row = {}
        for k, v in row.items():
            cleaned_row[normalize_col(k)] = clean_text(v)
        rows.append(cleaned_row)

    return fieldnames, rows

def parse_pipe_table(text):
    lines = [line.strip() for line in text.splitlines() if line.strip()]
    table_lines = [line for line in lines if "|" in line]

    if len(table_lines) < 3:
        return [], []

    filtered = []
    for line in table_lines:
        # skip separator rows like |----|----|
        test = line.replace("|", "").replace("-", "").replace(":", "").strip()
        if test == "":
            continue
        filtered.append(line)

    if len(filtered) < 2:
        return [], []

    header_line = filtered[0]
    headers = [normalize_col(x) for x in header_line.strip("|").split("|")]

    rows = []
    for line in filtered[1:]:
        vals = [clean_text(x) for x in line.strip("|").split("|")]
        if len(vals) != len(headers):
            continue
        row = dict(zip(headers, vals))
        rows.append(row)

    return headers, rows

def parse_dataset_text(text):
    # IMPORTANT: prefer pipe table first because Doc Extractor is producing that
    if looks_like_pipe_table(text):
        columns, rows = parse_pipe_table(text)
        if rows:
            return columns, rows, "pipe_table"

    # fallback to real CSV only if needed
    columns, rows = parse_csv_text(text)
    if rows:
        return columns, rows, "csv"

    return [], [], "unknown"

def find_col(columns, possible_names):
    normalized_map = {normalize_col(c): c for c in columns}

    for p in possible_names:
        p_norm = normalize_col(p)
        if p_norm in normalized_map:
            return normalized_map[p_norm]

    for c in columns:
        c_norm = normalize_col(c)
        for p in possible_names:
            p_norm = normalize_col(p)
            if p_norm in c_norm or c_norm in p_norm:
                return c
    return None

def top_n(d, n=5, reverse=True):
    return {k: round(v, 2) for k, v in sorted(d.items(), key=lambda x: x[1], reverse=reverse)[:n]}

def empty_response(message):
    return {
        "result": json.dumps({"error": message}, indent=2),
        "total_revenue": 0.0,
        "total_cost": 0.0,
        "total_profit": 0.0,
        "profit_margin": 0.0,
        "top_items_sales": {},
        "top_items_profit": {},
        "sales_by_date": {},
        "top_categories": {},
        "payment_mix": {},
        "top_items_sales_json": "{}",
        "top_items_profit_json": "{}",
        "sales_by_date_json": "{}",
        "top_categories_json": "{}",
        "payment_mix_json": "{}"
    }

def main(dataset_text, user_query: str) -> dict:
    if isinstance(dataset_text, list):
        text = "\n".join([str(x) for x in dataset_text if x is not None])
    else:
        text = str(dataset_text)

    text = preprocess_text(text)

    if not text:
        return empty_response("No dataset content found.")

    try:
        columns, rows, parse_mode = parse_dataset_text(text)

        if not rows:
            return empty_response("Could not parse the extracted dataset text.")

        # exact matching for your dataset
        date_col = find_col(columns, {"date"})
        order_id_col = find_col(columns, {"order_id"})
        item_col = find_col(columns, {"item_name"})
        category_col = find_col(columns, {"category"})
        qty_col = find_col(columns, {"quantity"})
        unit_price_col = find_col(columns, {"unit_price"})
        unit_cost_col = find_col(columns, {"unit_cost"})
        total_sales_col = find_col(columns, {"total_sales"})
        total_cost_col = find_col(columns, {"total_cost"})
        payment_col = find_col(columns, {"payment_method"})

        if not item_col:
            return empty_response(f"Item_Name column not found. Parsed columns: {columns}")

        if not total_sales_col:
            return empty_response(f"Total_Sales column not found. Parsed columns: {columns}")

        if not total_cost_col:
            return empty_response(f"Total_Cost column not found. Parsed columns: {columns}")

        total_revenue = 0.0
        total_cost = 0.0
        total_profit = 0.0
        order_ids = set()

        sales_by_item = defaultdict(float)
        profit_by_item = defaultdict(float)
        sales_by_date = defaultdict(float)
        sales_by_category = defaultdict(float)
        sales_by_payment = defaultdict(float)

        nonzero_revenue_rows = 0
        nonzero_cost_rows = 0

        for row in rows:
            item = clean_text(row.get(item_col, "")) or "Unknown"
            category = clean_text(row.get(category_col, "")) if category_col else "Unknown"
            date = clean_text(row.get(date_col, "")) if date_col else "Unknown"
            payment_method = clean_text(row.get(payment_col, "")) if payment_col else "Unknown"
            order_id = clean_text(row.get(order_id_col, "")) if order_id_col else ""

            revenue = safe_float(row.get(total_sales_col, 0))
            cost = safe_float(row.get(total_cost_col, 0))
            profit = revenue - cost

            if revenue != 0:
                nonzero_revenue_rows += 1
            if cost != 0:
                nonzero_cost_rows += 1

            total_revenue += revenue
            total_cost += cost
            total_profit += profit

            sales_by_item[item] += revenue
            profit_by_item[item] += profit
            sales_by_date[date] += revenue
            sales_by_category[category] += revenue
            sales_by_payment[payment_method] += revenue

            if order_id:
                order_ids.add(order_id)

        profit_margin = (total_profit / total_revenue * 100) if total_revenue else 0.0
        average_order_value = (total_revenue / len(order_ids)) if order_ids else 0.0

        top_sales_items = top_n(sales_by_item, 5, True)
        top_profit_items = top_n(profit_by_item, 5, True)
        low_profit_items = top_n(profit_by_item, 5, False)
        top_categories = top_n(sales_by_category, 5, True)
        payment_mix = top_n(sales_by_payment, 5, True)

        sales_by_date_sorted = {
            k: round(v, 2)
            for k, v in sorted(sales_by_date.items(), key=lambda x: x[0])[:30]
        }

        summary_output = {
            "summary_metrics": {
                "total_revenue": round(total_revenue, 2),
                "total_cost": round(total_cost, 2),
                "total_profit": round(total_profit, 2),
                "profit_margin_percent": round(profit_margin, 2),
                "total_orders": len(order_ids),
                "average_order_value": round(average_order_value, 2)
            },
            "business_trends_summary": {
                "top_items_by_sales": list(top_sales_items.keys()),
                "top_items_by_profit": list(top_profit_items.keys()),
                "bottom_items_by_profit": list(low_profit_items.keys()),
                "top_categories": list(top_categories.keys()),
                "top_payment_methods": list(payment_mix.keys())
            },
            "chart_ready_data_available": True,
            "parser_info": {
                "parse_mode": parse_mode,
                "row_count": len(rows),
                "nonzero_revenue_rows": nonzero_revenue_rows,
                "nonzero_cost_rows": nonzero_cost_rows
            },
            "mapped_columns": {
                "date": date_col,
                "order_id": order_id_col,
                "item_name": item_col,
                "category": category_col,
                "quantity": qty_col,
                "unit_price": unit_price_col,
                "unit_cost": unit_cost_col,
                "total_sales": total_sales_col,
                "total_cost": total_cost_col,
                "payment_method": payment_col
            }
        }

        return {
            "result": json.dumps(summary_output, indent=2),
            "total_revenue": round(total_revenue, 2),
            "total_cost": round(total_cost, 2),
            "total_profit": round(total_profit, 2),
            "profit_margin": round(profit_margin, 2),
            "top_items_sales": top_sales_items,
            "top_items_profit": top_profit_items,
            "sales_by_date": sales_by_date_sorted,
            "top_categories": top_categories,
            "payment_mix": payment_mix,
            "top_items_sales_json": json.dumps(top_sales_items),
            "top_items_profit_json": json.dumps(top_profit_items),
            "sales_by_date_json": json.dumps(sales_by_date_sorted),
            "top_categories_json": json.dumps(top_categories),
            "payment_mix_json": json.dumps(payment_mix)
        }

    except Exception as e:
        return {
            "result": json.dumps({
                "error": f"Failed to process dataset: {str(e)}"
            }, indent=2),
            "total_revenue": 0.0,
            "total_cost": 0.0,
            "total_profit": 0.0,
            "profit_margin": 0.0,
            "top_items_sales": {},
            "top_items_profit": {},
            "sales_by_date": {},
            "top_categories": {},
            "payment_mix": {},
            "top_items_sales_json": "{}",
            "top_items_profit_json": "{}",
            "sales_by_date_json": "{}",
            "top_categories_json": "{}",
            "payment_mix_json": "{}"
        }